[test]
preload = "./happydom.ts"

[install.lockfile]
save = true
exact = true

# always enable coverage
coverage = true
coverageSkipTestFiles = true
coverageReporter  = ["text", "lcov"]  # default ["text"]
coverageDir = "coverage"  # default "coverage"