[test]
preload = "./happydom.ts"

    # always enable coverage
coverage = true
coverageSkipTestFiles = true
coverageReporter  = ["text", "lcov"]  # default ["text"]
coverageDir = "coverage"  # default "coverage"